import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

import 'antd/dist/antd.css'
import '@/styles/index.css'
import { Layout } from 'antd'

import '@rainbow-me/rainbowkit/styles.css'
import { getDefaultWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit'
import { configureChains, createClient, WagmiConfig } from 'wagmi'
import { mainnet, goerli, foundry } from 'wagmi/chains'
import { alchemyProvider } from 'wagmi/providers/alchemy'
import { publicProvider } from 'wagmi/providers/public'

import MyContractsProvider from '@/components/web3/MyContractsProvider'
import Web3NavBar from '@/components/web3/Web3NavBar'

const { chains, provider } = configureChains(
  [foundry, mainnet, goerli],
  [
    alchemyProvider({ apiKey: process.env.ALCHEMY_API_KEY || '' }),
    publicProvider(),
  ]
)

const { connectors } = getDefaultWallets({
  appName: 'next-app',
  chains,
})

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
})

export default function App({ Component, pageProps }: AppProps) {
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <MyContractsProvider>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Layout>
            <Layout.Header>
              <Web3NavBar />
            </Layout.Header>
            <Layout.Content>
              <Component {...pageProps} />
            </Layout.Content>
            <Layout.Footer></Layout.Footer>
          </Layout>
        </MyContractsProvider>
      </RainbowKitProvider>
    </WagmiConfig>
  )
}
